### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by lsena** [lsena/fastfilter-elasticsearch-plugin#1]
https://github.com/lsena/fastfilter-elasticsearch-plugin/blob/master/src/main/java/org/elasticsearch/lsena/fastfilter/FastFilterPlugin.java#L162

Is this the fastest way to check the field value for the current doc?
If the field is _id, it seems to be deprecated

**Comment by anti-social** [comment]
An attempt to improve performance: https://github.com/anti-social/fastfilter-elasticsearch-plugin/commit/35caa9e3dad99ed3bc1eeb10a815f3a2e5c0b1ad

I could make a PR when have time.

**Comment by lsena** [comment]
> An attempt to improve performance: [anti-social@35caa9e](https://github.com/anti-social/fastfilter-elasticsearch-plugin/commit/35caa9e3dad99ed3bc1eeb10a815f3a2e5c0b1ad)
> 
> I could make a PR when have time.

Hi!
Thank you so much, I'll test it soon on my machine.

Did you manage to test it for correctness and performance on your end?

**Comment by anti-social** [comment]
All tests are passed.

I didn't test performance but I think it should be improved. There were eliminated 2 string comparisons and 1 hashmap lookup for every document.

**Comment by anti-social** [comment]
Also I think we should not support `keyword` fields.

**Comment by lsena** [comment]
Tested and everything seems to be working well.
I'll run performance tests later, but if you want to create a PR, I can merge it already.
Thank you!
